services:
  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
    volumes:
      - ./nats/nats.conf:/etc/nats/nats.conf
    command: ["-c", "/etc/nats/nats.conf"]
  middleware:
    build: .
    environment:
      NATS_URL: nats://nats:4222
      APP_PORT: 8080
      RUST_LOG: debug
    ports:
      - 8080:8080
    depends_on:
      - nats
